CREATE TABLE warehouse (
  W_ID INT PRIMARY KEY,
  W_NAME VARCHAR(10) NOT NULL,
  W_STREET_1 VARCHAR(20) NOT NULL,
  W_STREET_2 VARCHAR(20) NOT NULL,
  W_CITY VARCHAR(20) NOT NULL,
  W_STATE CHAR(2) NOT NULL,
  W_ZIP CHAR(9) NOT NULL,
  W_TAX DECIMAL(4,4) NOT NULL,
  W_YTD DECIMAL(12,2) NOT NULL
);
